

migrate_synonyms:
  cron: "0 */6 * * *" # execute at minute 0 past every 6th hour.
  class: "Migrators::SynonymsWorker"
  queue: migrations

migrate_queries_counters:
  cron: "*/10 * * * *" # At every 10th minute
  class: "UserQueryWorker"
  queue: low

