

migrate_synonyms:
  cron: "0 */6 * * *" # execute at minute 0 past every 6th hour.
  class: "Migrators::SynonymsWorker"
  queue: migrations

migrate_queries_counters:
  cron: "*/10 * * * *" # At every 10th minute
  class: "UserQueryWorker"
  queue: low

keep_it_hot:
  cron: "0 */2 * * *" # At every 2th hour
  class: "Crawlers::KeepItHotWorker"
  queue: heater

reindex_species:
  cron: "*/10 * * * *" # At every 10th minute
  class: "Search::ReindexSpeciesWorker"
  queue: reindex

