---
:concurrency: 5
production:
  :concurrency: 5
:queues:
  - critical
  - default
  - crawlers
  - checks
  - migrations
  - low
  - heater
  - reindex
  - searchkick
:process_limits:
  heater: 2
  critical: 50
  searchkick: 20
  searchkick: 20
  default: 20
  crawlers: 5
  checks: 5
  migrations: 5
  low: 5
